# Generated by Django 3.0.7 on 2020-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200627_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
